replicas: 1
externalPort: 80
image:
  registry: unquabain
  repository: mazer
  tag: latest
  containerPort: 80
network:
  host: mazer.4zb.org
  cert_issuer: letsencrypt-prod
  cert_secret: mazer-tls
  ingress_class: nginx
