apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.externalPort }}
    targetPort: {{ .Values.image.containerPort }}
  selector:
    app: {{ .Chart.Name }}
